const scene=document.querySelector('#scene'),visual=document.querySelector('#visual');
const studies={estate:['REAL ESTATE / FRAME','공간을 넘어,\n삶의 기준으로.','열 개의 회전 셔터가 건축의 한 장면을 완성합니다.','01 / ROTATING SHUTTERS'],stocks:['MARKET / PULSE','흐름의 차이를\n발견하다.','엇갈리는 이미지 잔상과 라이트 스캔으로 표현한 시장의 리듬.','02 / TEMPORAL SLIT SCAN'],coin:['DIGITAL ASSETS / ORBIT','가치의\n새로운 궤도.','서로 다른 축으로 회전하는 빛의 링. 중심에 남는 하나의 가치.','03 / GYROSCOPIC ORBITS'],chain:['INFRASTRUCTURE / FOLD','가능성을 펼치다.\n연결을 완성하다.','접힌 여섯 개의 면이 펼쳐지며 하나의 구조가 됩니다.','04 / ACCORDION REVEAL'],together:['','','','05 / TOGETHER · 20 SEC']};
let key='estate',paused=matchMedia('(prefers-reduced-motion: reduce)').matches;
function photo(){let e=document.createElement('div');e.className='photo';e.style.backgroundImage=`url(assets/${key}.jpg)`;return e}
function select(k){key=k;scene.className=k+(paused?' paused':'');visual.replaceChildren();const a=studies[k];['eyebrow','headline','description','effect'].forEach((id,i)=>document.getElementById(id).textContent=a[i]);document.querySelectorAll('[data-key]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.key===k)));history.replaceState(null,'','#'+k);
if(k==='together'){const v=document.createElement('video');v.src='assets/together.mp4';v.poster='assets/together.jpg';v.controls=true;v.playsInline=true;v.muted=true;v.loop=true;visual.append(v);if(!paused)v.play().catch(()=>{});return}
if(k==='estate'||k==='chain'){let n=k==='estate'?10:6;for(let i=0;i<n;i++){let e=document.createElement('div');e.className=k==='estate'?'shutter':'fold';e.style.cssText=`--i:${i};left:${i*100/n}%;width:${100/n+.05}%;`;e.append(photo());visual.append(e)}}
else{visual.append(photo());if(k==='stocks'){for(let i=0;i<8;i++){let e=document.createElement('div');e.className='scan';e.style.cssText=`--i:${i};--x:${30+i*8}%;background-image:url(assets/stocks.jpg)`;visual.append(e)}let b=document.createElement('div');b.className='scanbeam';visual.append(b)}else{let space=document.createElement('div');space.className='orbit-space';for(let i=0;i<3;i++){let e=document.createElement('div');e.className='ring';e.style.setProperty('--i',i);space.append(e)}visual.append(space)}}resize()}
function resize(){visual.style.setProperty('--w',visual.clientWidth+'px')}addEventListener('resize',resize);document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>select(b.dataset.key));const pause=document.querySelector('#pause');function sync(){scene.classList.toggle('paused',paused);pause.textContent=paused?'재생':'일시정지';let v=visual.querySelector('video');if(v){if(paused)v.pause();else v.play().catch(()=>{})}}pause.onclick=()=>{paused=!paused;sync()};document.querySelector('#replay').onclick=()=>{select(key);sync()};select(studies[location.hash.slice(1)]?location.hash.slice(1):'estate');sync();
