const hero=document.querySelector('main'),replay=document.querySelector('#replay'),skip=document.querySelector('#skip'),reduce=matchMedia('(prefers-reduced-motion: reduce)');let timer;function stop(){clearTimeout(timer);hero.classList.remove('opening');replay.disabled=false;skip.hidden=true}function play(){stop();if(reduce.matches)return;void hero.offsetWidth;hero.classList.add('opening');replay.disabled=true;skip.hidden=false;timer=setTimeout(stop,2700)}replay.onclick=play;skip.onclick=stop;reduce.addEventListener('change',()=>{if(reduce.matches)stop()});const img=document.querySelector('.food');if(img.complete&&img.naturalWidth)play();else img.addEventListener('load',play,{once:true});

// Ambient motion stays separate from the food photograph so the food stays sharp.
const atmosphere=document.createElement('div');atmosphere.className='atmosphere';atmosphere.setAttribute('aria-hidden','true');
if(document.body.classList.contains('jokbal')){
 atmosphere.innerHTML='<svg class="steam" viewBox="0 0 600 400" fill="none"><defs><filter id="soft"><feGaussianBlur stdDeviation="5"/></filter></defs><g filter="url(#soft)" stroke="#f7eedc" stroke-linecap="round"><path class="wisp w1" d="M130 380 C80 330 190 290 140 230 S105 130 170 55"/><path class="wisp w2" d="M310 380 C370 320 255 270 315 205 S350 105 300 25"/><path class="wisp w3" d="M460 380 C420 320 510 270 465 215 S420 120 470 50"/></g></svg>';
}else{
 atmosphere.innerHTML='<span class="taste spicy">매콤!</span><span class="taste chewy">쫀득!</span><span class="taste crispy">바삭!</span><svg class="doodles" viewBox="0 0 1000 650" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round"><g class="rays r1"><path d="M480 100l-15-25M510 90l2-30M540 98l18-24"/></g><g class="rays r2"><path d="M805 365l30-13M815 393l34 3M808 420l29 18"/></g><g class="rays r3"><path d="M335 470l-23-15M323 495l-29 1M334 522l-22 16"/></g></svg>';
}
hero.append(atmosphere);
const ambientToggle=document.createElement('button');ambientToggle.id='ambient-toggle';ambientToggle.type='button';let ambientPaused=reduce.matches;function ambientState(){hero.classList.toggle('ambient-paused',ambientPaused);ambientToggle.textContent=ambientPaused?'효과 재생':'효과 멈춤';ambientToggle.setAttribute('aria-pressed',String(!ambientPaused))}ambientToggle.onclick=()=>{ambientPaused=!ambientPaused;ambientState()};hero.append(ambientToggle);ambientState();reduce.addEventListener('change',()=>{ambientPaused=reduce.matches;ambientState()});
